# Generated by Django 4.2.1 on 2024-09-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfcargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfcargo',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
