# Generated by Django 5.1.2 on 2025-02-27 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tfcargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tfcargo',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tfcargo',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='tfcargo.category'),
        ),
        migrations.AddField(
            model_name='tfcargo',
            name='distance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tfcargo', to='tfcargo.distance'),
        ),
        migrations.AddField(
            model_name='tfcargo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tfcargo.tagpost'),
        ),
        migrations.AddIndex(
            model_name='tfcargo',
            index=models.Index(fields=['-time_create'], name='tfcargo_tfc_time_cr_1f0289_idx'),
        ),
    ]
