# Generated by Django 4.2.1 on 2024-09-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfcargo', '0002_tfcargo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfcargo',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
