# Generated by Django 4.2.1 on 2024-09-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfcargo', '0004_category_tfcargo_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfcargo',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tfcargo.category'),
        ),
    ]
