# Generated by Django 4.2.1 on 2024-09-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfcargo', '0005_alter_tfcargo_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tfcargo',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='tfcargo.category'),
        ),
        migrations.AddField(
            model_name='tfcargo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tfcargo.tagpost'),
        ),
    ]
