# Generated by Django 4.2.1 on 2024-10-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfcargo', '0006_tagpost_alter_tfcargo_cat_tfcargo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfcargo',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
