# Generated by Django 5.1.2 on 2024-12-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfcargo', '0009_uploadfiles_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfcargo',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
